environment:
  matrix:
  - nodejs_version: "7"
  - nodejs_version: "9"
  PINGY_GITHUB_TOKEN:
    secure: SVLm+MLbe5h3HXFxDF5HmHrhYm8RGh87f3u5puMzSTffgtn88a2+dkN+VgTz9zJL

install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor-retry call npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
